version: "3"
services:
  library-backend:
    image: library:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8080"
    depends_on:
      - pg-library-db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg-library-db/library_db

  pg-library-db:
    image: postgres:14.5-alpine
    container_name: library_db
    environment:
      POSTGRES_DB: "library_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - library-db:/var/lib/postgresql/data
    ports:
      - "15432:5432"
volumes:
  library-db: