version: "3"
services:
  pg-library-db:
    image: postgres:14.5-alpine
    container_name: library_db
    environment:
      POSTGRES_DB: "library_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - library-db:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: library
    volumes:
      - ./environment/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - library-mongodb:/data/db
      - library-mongo-config:/data/configdb

  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass 123456
    volumes:
      - library-redis:/data

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./environment/minio/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address :9001

volumes:
  library-db:
  library-mongodb:
  library-mongo-config:
  library-redis:
  storage-minio: