apiVersion: apps/v1
kind: Deployment
metadata:
  name: library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
        - name: library
          image: daniil141980/library:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:15432/library_db
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: library
spec:
  selector:
    app: library
  ports:
     - port: 8181
       targetPort: 8080
  type: LoadBalancer