spring:
  datasource:
    url: 'jdbc:postgresql://localhost:15432/library_db'
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/library
  cache:
    type: redis
    cache-names: redis-cashe
    redis:
      time-to-live: 30000
  redis:
    host: localhost
    port: 6379
    password: YXNkZmFzZGY=
  liquibase:
    change-log: classpath:db/changelog/main-changelog.yaml

minio:
  url: http://localhost:9000
  port: 9000
  accessKey: user
  secretKey: password
  secure: false
  bucket: minio-storage
  image-size: 10485760

server:
  port: 8080
  address: localhost
